# Site settings
title: The Gazelle
description: > # this means to ignore newlines until "baseurl:"
  What is love? Baby, don't hurt me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thegazelle.github.io" # the base hostname & protocol for your site
github_username:  TheGazelle
header-img: img/bamboo.png

highlighter: false

# Build settings
markdown: kramdown
